exports.getData = (req, res) => {
  res.status(200).json({
    code: 200,
    message: 'success',
    materials: materials,
    formulars: formulars
  })
}

exports.calculate = (req, res) => {
  let from = req.body.from;
  let to = req.body.to;

  calculate(from, to, 0, from);
  setTimeout(() => {
	result = result.sort((a, b) => {
		return a.index < b.index ? -1 : a.index > b.index ? 1 : 0;
	});
	res.status(200).json({
		code: 200,
		message: 'success',
		list: result
	});
	result = []
  }, 3000);
}

var result = [];
const maxStep = 4;

const calculate = (from, to, index, path) => {
  if (index > 0 && from === to) {
    result.push({index: index, path: path});
  }
  else if (index < maxStep) {
    let materialIndex = materials.findIndex((material) => {
      return material.material === from;
    })
    let categorys = [];
    if (materialIndex >= 0) categorys = materials[materialIndex].category;

    formulars.forEach((formular) => {
      if (formular.element.includes(from) && formular.material !== from) calculate(formular.material, to, index+1, `${path} > ${formular.material}`);
      categorys.forEach((category) => {
        if (formular.element.includes(category)) calculate(formular.material, to, index+1, `${path} > ${formular.material}`);
      })
    })
  }
}

// material: material's name, category: material's category
const materials = [
  {material: '톤', category: ['(마법의풀)', '(식물류)', '(약재료)']},
  {material: '키큰 톤', category: ['(마법의풀)', '(식물류)', '(약재료)']},
  {material: '세쌍둥이 톤', category: ['(마법의풀)', '(식물류)', '(신비의힘)']},
  {material: '미스틱 허브', category: ['(마법의풀)', '(식물류)', '(약재료)']},
  {material: '코발트 풀', category: ['(식물류)', '(물)', '(향기)']},
  {material: '윙플랜트', category: ['(식물류)', '(약재료)']},
  {material: '황금나뭇잎', category: ['(식물류)', '(약재료)']},
  {material: '성게', category: ['(식물류)', '(식재)']},
  {material: '바이체 보리', category: ['(식물류)']},
  {material: '촉촉한 풀', category: ['(식물류)', '(약재료)', '(에릭실)']},
  {material: '야면화', category: ['(식물류)', '(연료)', '(실소재)']},
  {material: '백설풀', category: ['(식물류)', '(꽃)', '(약재료)']},
  {material: '붉은 꽃', category: ['(식물류)', '(꽃)']},
  {material: '푸른 꽃', category: ['(식물류)', '(꽃)', '(약재료)']},
  {material: '초록 꽃', category: ['(식물류)', '(꽃)']},
  {material: '노란 꽃', category: ['(식물류)', '(꽃)', '(향기)']},
  {material: '자주색 꽃', category: ['(식물류)', '(꽃)', '(독재료)']},
  {material: '메르베유 루즈', category: ['(식물류)', '(꽃)', '(향기)']},
  {material: '둔켈하이트', category: ['(식물류)', '(꽃)', '(약재료)']},
  {material: '별의 꽃', category: ['(식물류)', '(꽃)', '(신비의힘)']},
  {material: '벌집', category: ['(벌집)', '(화약)']},
  {material: '은색 벌집', category: ['(벌집)', '(화약)']},
  {material: '금색 벌집', category: ['(벌집)', '(화약)', '(보석)']},
  {material: '과자 벌집', category: ['(벌집)', '(과자)']},
  {material: '감로의 열매', category: ['(과일)', '(물)', '(향기)']},
  {material: '별의 열매', category: ['(과일)', '(향기)']},
  {material: '장딸기', category: ['(과일)', '(약재료)']},
  {material: '눈의 여왕', category: ['(과일)', '(물)', '(신비의힘)']},
  {material: '점액 버섯', category: ['(버섯)', '(기름)']},
  {material: '요정의 양산', category: ['(버섯)', '(식물류)', '(식재)']},
  {material: '야미요타케', category: ['(버섯)', '(독재료)']},
  {material: '연기 버섯', category: ['(버섯)', '(기체)', '(향기)']},
  {material: '토란', category: ['(식재)', '(식물류)']},
  {material: '우유', category: ['(식재)', '(물)']},
  {material: '신선한 고기', category: ['(식재)']},
  {material: '짐승 고기', category: ['(식재)']},
  {material: '무언가의 알', category: ['(식재)']},
  {material: '대형 알', category: ['(식재)', '(기름)']},
  {material: '양모', category: ['(동물소재)', '(실소재)', '(연료)']},
  {material: '마조의 깃털', category: ['(동물소재)', '(실소재)']},
  {material: '그리폰의 날개', category: ['(동물소재)', '(실소재)']},
  {material: '박쥐의 날개', category: ['(동물소재)', '(식재)', '(마법의도구)']},
  {material: '거북손', category: ['(동물소재)', '(식재)', '(약재료)']},
  {material: '동물의 가죽', category: ['(동물소재)']},
  {material: '튼튼한 뼈', category: ['(동물소재)', '(약재료)']},
  {material: '일각', category: ['(동물소재)', '(약재료)']},
  {material: '거수의 뼈', category: ['(동물소재)']},
  {material: '사악한 송곳니', category: ['(동물소재)', '(독재료)']},
  {material: '젤리 젬', category: ['(동물소재)', '(보석)']},
  {material: '토끼털', category: ['(동물소재)', '(실소재)']},
  {material: '커다란 비늘', category: ['(동물소재)', '(신비의힘)']},
  {material: '사악한 뼈', category: ['(동물소재)', '(독재료)']},
  {material: '슈테른 버그', category: ['(곤충)']},
  {material: '베이비 빌름', category: ['(곤충)', '(식재)']},
  {material: '라이덴 드라군', category: ['(곤충)']},
  {material: '코멧 나비', category: ['(곤충)']},
  {material: '성게 바구미', category: ['(곤충)']},
  {material: '투구 메뚜기', category: ['(곤충)', '(식재)']},
  {material: '킬러비', category: ['(곤충)', '(독재료)']},
  {material: '젬 플라이', category: ['(곤충)', '(보석)']},
  {material: '예쁜 조개껍질', category: ['(어패류)', '(약재료)']},
  {material: '워셔', category: ['(어패류)', '(식재)']},
  {material: '나비 고기', category: ['(어패류)', '(식재)']},
  {material: '컴버', category: ['(어패류)', '(식재)']},
  {material: '무셸', category: ['(어패류)', '(식재)']},
  {material: '크리브', category: ['(어패류)', '(식재)']},
  {material: '집게 새우', category: ['(어패류)', '(식재)']},
  {material: '풍선어', category: ['(어패류)', '(독재료)']},
  {material: '웜 피시', category: ['(어패류)', '(약재료)']},
  {material: '지배자', category: ['(어패류)', '(기름)']},
  {material: '작열의 지배자', category: ['(어패류)', '(연료)']},
  {material: '레이피어 피시', category: ['(어패류)', '(식재)']},
  {material: '푸니푸니 구슬 청', category: ['(푸니푸니구슬)', '(식재)', '(신비의힘)']},
  {material: '푸니푸니 구슬 녹', category: ['(푸니푸니구슬)', '(식재)', '(신비의힘)']},
  {material: '푸니푸니 구슬 적', category: ['(푸니푸니구슬)', '(식재)', '(신비의힘)']},
  {material: '푸니푸니 구슬 금', category: ['(푸니푸니구슬)', '(식재)', '(신비의힘)']},
  {material: '용의 비늘', category: ['(용소재)', '(약재료)', '(에릭실)']},
  {material: '용핵', category: ['(용소재)', '(보석)', '(신비의힘)']},
  {material: '용의 혈정', category: ['(용소재)', '(물)', '(에릭실)']},
  {material: '위대한 꼬리', category: ['(용소재)', '(식재)']},
  {material: '식용수', category: ['(물)']},
  {material: '우물물', category: ['(물)']},
  {material: '톡톡물', category: ['(물)', '(기체)']},
  {material: '찌릿찌릿물', category: ['(물)', '(신비의힘)']},
  {material: '심층수', category: ['(물)', '(약재료)']},
  {material: '수상한 액체', category: ['(물)', '(독재료)']},
  {material: '프니의 체액', category: ['(물)', '(약재료)']},
  {material: '별모래 물', category: ['(물)', '(모래)', '(신비의힘)']},
  {material: '성수', category: ['(물)', '(약재료)', '(신비의힘)']},
  {material: '만년 무빙', category: ['(물)', '(신비의힘)']},
  {material: '찢어진 종잇조각', category: ['(종이)', '(연료)']},
  {material: '교회의 부적', category: ['(종이)', '(연료)']},
  {material: '고급 부적', category: ['(종이)', '(연료)']},
  {material: '경건한 신자용 부적', category: ['(종이)', '(연료)', '(마법의도구)']},
  {material: '바켄의 브로마이드', category: ['(종이)', '(연료)']},
  {material: '식물유', category: ['(연료)', '(기름)']},
  {material: '기름나무 열매', category: ['(연료)', '(기름)']},
  {material: '자연광물유', category: ['(연료)', '(광석)', '(기름)']},
  {material: '키퍼', category: ['(목재)', '(연료)']},
  {material: '레이븐우드', category: ['(목재)']},
  {material: '아로마 홀츠', category: ['(목재)', '(향기)']},
  {material: '점은실', category: ['(실소재)']},
  {material: '금견실', category: ['(실소재)', '(동물소재)', '(연료)']},
  {material: '천연비료', category: ['(점토)', '(약재료)']},
  {material: '붉은 모래', category: ['(모래)', '(점토)']},
  {material: '검은 모래', category: ['(모래)', '(점토)']},
  {material: '하얀 모래', category: ['(모래)']},
  {material: '사정석', category: ['(모래)', '(광석)']},
  {material: '백회색', category: ['(광석)']},
  {material: '황금색 암석', category: ['(광석)', '(화약)']},
  {material: '깨진 석재', category: ['(광석)', '(점토)']},
  {material: '그라비석', category: ['(광석)', '(신비의힘)']},
  {material: '에르토나 수정', category: ['(광석)', '(보석)', '(신비의힘)']},
  {material: '아이젠 광석', category: ['(광석)']},
  {material: '라이덴 광석', category: ['(광석)']},
  {material: '쿠플흐 광석', category: ['(광석)']},
  {material: '카엔석', category: ['(광석)', '(화약)']},
  {material: '하크레이석', category: ['(광석)']},
  {material: '옥강석', category: ['(광석)', '(금속)']},
  {material: '칠흑의 도목석', category: ['(광석)', '(식물류)']},
  {material: '소울 스톤', category: ['(광석)', '(금속)']},
  {material: '물결 바위', category: ['(광석)']},
  {material: '자철암', category: ['(광석)']},
  {material: '킴버 광석', category: ['(광석)']},
  {material: '칠흑의 성석', category: ['(광석)']},
  {material: '정령석', category: ['(광석)', '(마법의도구)', '(신비의힘)']},
  {material: '쌍색 커런덤', category: ['(광석)', '(보석)', '(약재료)']},
  {material: '수정 조각', category: ['(보석)']},
  {material: '창강석', category: ['(보석)', '(광석)']},
  {material: '심핵', category: ['(보석)', '(신비의힘)', '(에릭실)']},
  {material: '소형 하겔상', category: ['(금속)', '(신비의힘)']},
  {material: '펜데록', category: ['(신비의힘)', '(보석)']},
  {material: '혼돈의 진흙', category: ['(기름)', '(화약)', '(점토)']},
  {material: '심판을 부르는 돌', category: ['(물)', '(광석)', '(금속)']},
  {material: '터미너스 리프', category: ['(목재)', '(신비의힘)', '(에릭실)']},
  {material: '활성제', category: ['(활성)']},
  {material: '바르하이트', category: ['(활성)']},
  {material: '액화금속', category: ['(활성)']},
  {material: '가열도석', category: ['(활성)']},
  {material: '과반응 유지', category: ['(활성)']},
  {material: '적기문석', category: ['(활성)']},
  {material: '성산', category: ['(활성)']},
  {material: '용산', category: ['(활성)']},
  {material: '심창석', category: ['(활성)']},
  {material: '물의 결정', category: ['(활성)']},
  {material: '마블 암염', category: ['(활성)']},
  {material: '작열의 용광석', category: ['(활성)']},
  {material: '알베리히', category: ['(활성)']},
  {material: '자침', category: ['(활성)']},
  {material: '빛의 가루', category: ['(활성)']},
  {material: '올드 스톤', category: ['(활성)']},
  {material: '곤충 호박', category: ['(활성)']},
  {material: '천로주정', category: ['(활성)']},
  {material: '시간 지킴이 꽃', category: ['(활성)']},
  {material: '태고의 물', category: ['(활성)']},
  {material: '용의 눈', category: ['(활성)']},
  {material: '성게 주머니', category: ['(폭탄)']},
  {material: '프람', category: ['(폭탄)']},
  {material: '레헤른', category: ['(폭탄)']},
  {material: '도나 스톤', category: ['(폭탄)']},
  {material: '크래프트', category: ['(폭탄)']},
  {material: '루프트', category: ['(폭탄)']},
  {material: '오리프람', category: ['(폭탄)']},
  {material: '슈탈 레헤른', category: ['(폭탄)']},
  {material: '도나 크리스털', category: ['(폭탄)']},
  {material: '루프트 아이젠', category: ['(폭탄)']},
  {material: '방랑하는 지구본', category: ['(폭탄)', '(마법의도구)']},
  {material: '신의 유실물', category: ['(폭탄)', '(마법의도구)']},
  {material: '깜짝 선물', category: ['(마법의도구)']},
  {material: '천계의 대청소', category: ['(폭탄)', '(마법의도구)']},
  {material: 'N/A', category: ['(폭탄)']},
  {material: '원초의 불씨', category: ['(폭탄)', '(마법의도구)']},
  {material: '종말의 불씨', category: ['(폭탄)']},
  {material: '일구입혼 메테오 볼', category: ['(폭탄)']},
  {material: '하이터 슈토름', category: ['(마법의도구)']},
  {material: '슈네 슈토름', category: ['(마법의도구)']},
  {material: '쾌활한 장난감 상자', category: ['(마법의도구)']},
  {material: '리퓨얼 패트', category: ['(약품)']},
  {material: '소박한 구운과자', category: ['(식품)', '(과자)']},
  {material: '푸니젤리', category: ['(식품)', '(과자)', '(신비의힘)']},
  {material: '리퓨얼 보틀', category: ['(약품)']},
  {material: '원초적 힘고기', category: ['(식품)']},
  {material: '프루티', category: ['(식품)', '(향기)']},
  {material: '산들바람 아로마', category: ['(약품)', '(기체)']},
  {material: '허니 시럽', category: ['(약품)']},
  {material: '생명의 꿀', category: ['(약품)', '(신비의힘)']},
  {material: '라위의 비약', category: ['(약품)', '(신비의힘)']},
  {material: '신비의 영약', category: ['(약품)', '(에릭실)']},
  {material: '특제 핫케이크', category: ['(식품)', '(과자)']},
  {material: '스위티', category: ['(식품)']},
  {material: '빨강 푸니젤리', category: ['(식품)', '(과자)', '(신비의힘)']},
  {material: '재생의 이슬', category: ['(약품)', '(에릭실)']},
  {material: '소악마의 장난', category: ['(마법의도구)']},
  {material: '퓨어 아로마', category: ['(약품)', '(향기)']},
  {material: '산성 안개구름', category: ['(약품)', '(기체)']},
  {material: '메디아 비독', category: ['(약품)', '(독재료)']},
  {material: '암흑수', category: ['(약품)', '(독재료)']},
  {material: '만능 액막이 향', category: ['(약품)', '(향기)']},
  {material: '정령의 장막', category: ['(직물)']},
  {material: '영웅의 환약', category: ['(약품)']},
  {material: '트리톤의 소라고둥', category: ['(마법의도구)']},
  {material: '힘멜 릴리프', category: ['(마법의도구)']},
  {material: '천매간', category: ['(마법의도구)', '(종이)']},
  {material: '프리즈마 크리스털', category: ['(마법의도구)', '(보석)']},
  {material: '빙무의 스틱', category: ['(마법의도구)']},
  {material: '나선 시계판', category: ['(마법의도구)', '(신비의힘)']},
  {material: '별의 분무', category: ['(마법의도구)']},
  {material: '흑백의 타로', category: ['(마법의도구)']},
  {material: '피전 블러드 오일', category: ['(마법의도구)']},
  {material: '낚싯대', category: ['(채집도구)', '(목재)']},
  {material: '고품질 낚싯대', category: ['(채집도구)', '(목재)']},
  {material: '신간 르베르크라운', category: ['(채집도구)', '(목재)']},
  {material: '벌레망', category: ['(채집도구)', '(실소재)']},
  {material: '경량 벌레망', category: ['(채집도구)', '(실소재)']},
  {material: '물주머니', category: ['(채집도구)']},
  {material: '특별 영양제', category: ['(약품)']},
  {material: '특별비약영양제', category: ['(채집도구)']},
  {material: '작은 요정의 가루', category: ['(채집도구)', '(직물)', '(기체)']},
  {material: '풍신의 자루', category: ['(채집도구)', '(직물)', '(기체)']},
  {material: '특제 백팩', category: ['(직물)']},
  {material: '채집 장갑', category: ['(채집도구)', '(직물)']},
  {material: '발파용 프람', category: ['(폭탄)']},
  {material: '초 발파용 프램', category: ['(폭탄)']},
  {material: '중화제 적', category: ['(중화제)']},
  {material: '중화제 청', category: ['(중화제)']},
  {material: '중화제 황', category: ['(중화제)']},
  {material: '중화제 녹', category: ['(중화제)']},
  {material: '중화제 자', category: ['(중화제)']},
  {material: '만능 중화제 무지개', category: ['(중화제)']},
  {material: '증류수', category: ['(물)']},
  {material: '꿀', category: ['(식재)']},
  {material: '보릿가루', category: ['(식재)', '(화약)']},
  {material: '업콜', category: ['(물)', '(연료)', '(약재료)']},
  {material: '퓨어 오일', category: ['(연료)', '(기름)']},
  {material: '제텔', category: ['(종이)', '(연료)']},
  {material: '무두질액', category: ['(약품)', '(독재료)']},
  {material: '무두질 가죽', category: ['(동물소재)', '(방어구소재)']},
  {material: '다색 염료', category: ['(약품)']},
  {material: '폴리시', category: ['(점토)', '(모래)']},
  {material: '연금점토', category: ['(점토)', '(에릭실)']},
  {material: '원초의 재', category: ['(화약)', '(에릭실)', '(약품)']},
  {material: '지구의 구슬', category: ['(목재)', '(마법의도구)']},
  {material: '맛있어 보이는 떡밥', category: ['(식품)', '(점토)']},
  {material: '잉곳', category: ['(무기소재)', '(금속)']},
  {material: '실베리아', category: ['(무기소재)', '(금속)']},
  {material: '골드 아이젠', category: ['(무기소재)', '(금속)']},
  {material: '하르모늄', category: ['(무기소재)', '(금속)', '(신비의힘)']},
  {material: '클로스', category: ['(방어구소재)', '(직물)']},
  {material: '모프코트', category: ['(방어구소재)', '(직물)']},
  {material: '플뤼겔', category: ['(방어구소재)', '(직물)']},
  {material: '벨베티스', category: ['(방어구소재)', '(직물)', '(신비의힘)']},
  {material: '제트 원석', category: ['(광석)', '(식물류)', '(보석)']},
  {material: '그라나트 원석', category: ['(광석)', '(보석)']},
  {material: '에메랄드 원석', category: ['(광석)', '(보석)']},
  {material: '사파이어스 원석', category: ['(광석)', '(보석)']},
  {material: '루비나이트 원석', category: ['(광석)', '(보석)']},
  {material: '금강 원석', category: ['(보석)']},
  {material: '제트', category: ['(보석)', '(식물류)']},
  {material: '그라나트', category: ['(보석)']},
  {material: '에메랄드', category: ['(보석)']},
  {material: '사파이어스', category: ['(보석)']},
  {material: '루비나이트', category: ['(보석)']},
  {material: '금강석', category: ['(보석)']},
  {material: '마르모아 코메트', category: ['(보석)', '(신비의힘)']},
  {material: '심홍석', category: ['(동물소재)', '(화약)', '(에릭실)']},
  {material: '현자의 돌', category: ['(물)', '(약재료)', '(에릭실)']},
  {material: '귀여운 현자의 돌', category: ['(물)', '(약재료)', '(에릭실)']},
  {material: '꿈의 붓', category: ['(마법의도구)', '(연료)']},
  {material: '꿈의 붓?', category: ['(연료)']},
  {material: '고고한 마음의 물감', category: ['(마법의도구)']},
  {material: '고상한 파도의 물감', category: ['(마법의도구)']},
  {material: '얼어붙은 심상의 물감', category: ['(마법의도구)']},
  {material: '틈새를 떠도는 물감', category: ['(마법의도구)']},
  {material: '영원한 천상의 물감', category: ['(마법의도구)']},
  {material: '꿈꾸는 밤하늘의 물감', category: ['(마법의도구)']},
  {material: '사악한 어둠에 떨어진 물감', category: ['(마법의도구)']},
  {material: '끝이 없는 일기장', category: ['(마법의도구)', '(종이)', '(연료)']},
  {material: '커뮤테이션', category: ['(마법의도구)', '(약품)']},
  {material: '아다렛트 장미보관', category: ['(마법의도구)']},
  {material: '얼음상자', category: ['(마법의도구)']},
  {material: '도나 엔데커', category: ['(마법의도구)']},
  {material: '냉풍 기관', category: ['(마법의도구)', '(기체)']},
  {material: '고블릿', category: ['(마법의도구)']},
  {material: '은식기 세트', category: ['(금속)']},
  {material: '위장약', category: ['(약품)']},
  {material: '감기 특효약', category: ['(약품)']},
  {material: '액화용제', category: ['(약품)']},
  {material: '활력의 얼리언스', category: ['(무기코어)']},
  {material: '용맹의 얼리언스', category: ['(무기코어)']},
  {material: '맹력의 브라존', category: ['(무기코어)']},
  {material: '신력의 브라존', category: ['(무기코어)']},
  {material: '광속의 오브', category: ['(무기코어)']},
  {material: '신속의 오브', category: ['(무기코어)']},
  {material: '쾌도난마의 엠블럼', category: ['(무기코어)']},
  {material: '일기당천 오르뎀', category: ['(무기코어)']},
  {material: '예지의 리안', category: ['(무기코어)']},
  {material: '쿼츠 기어', category: ['(무기파츠)']},
  {material: '카보숑 기어', category: ['(무기파츠)']},
  {material: '제트 기어', category: ['(무기파츠)']},
  {material: '에메랄드 파멀', category: ['(무기파츠)']},
  {material: '사파이어스 파멀', category: ['(무기파츠)']},
  {material: '루비나이트 파멀', category: ['(무기파츠)']},
  {material: '마르모어 기어', category: ['(무기파츠)']},
  {material: '금강 룬스톤', category: ['(무기파츠)']},
  {material: '그나데링', category: ['(장식품)']},
  {material: '엔젤리본', category: ['(장식품)']},
  {material: '불꽃의 탈리스만', category: ['(장식품)']},
  {material: '바람의 탈리스만', category: ['(장식품)']},
  {material: '얼음의 탈리스만', category: ['(장식품)']},
  {material: '뇌환의 탈리스만', category: ['(장식품)']},
  {material: '마석 체인', category: ['(장식품)']},
  {material: '너클 가드', category: ['(장식품)']},
  {material: '행운의 금화', category: ['(장식품)']},
  {material: '안쥬 파뤼르', category: ['(장식품)']},
  {material: '용린의 목걸이', category: ['(장식품)']}
]

// material: material of synthesis's result, element: elements of formula
const formulars = [
  {material: '성게 주머니', element: ['성게', '(화약)']},
  {material: '프람', element: ['카엔석', '(화약)', '(연료)']},
  {material: '오리프람', element: ['프람', '(폭탄)', '(기름)', '(중화제)']},
  {material: '크래프트', element: ['성게 주머니', '(금속)', '(중화제)']},
  {material: '레헤른', element: ['하크레이석', '(물)', '(중화제)']},
  {material: '슈탈 레헤른', element: ['레헤른', '만년무빙', '(물)', '(중화제)']},
  {material: '도나 스톤', element: ['라이덴 광석', '(점토)', '(중화제)']},
  {material: '도나 크리스털', element: ['도나 스톤', '옥강석', '(보석)', '(중화제)']},
  {material: '루프트', element: ['우이플랜트', '(기체)', '(연료)']},
  {material: '루프트 아이젠', element: ['루프트', '(화약)', '(금속)', '(중화제)']},
  {material: '방랑하는 지구본', element: ['지구의 구슬', '(광석)', '(금속)', '(신비의힘)']},
  {material: '신의 유실물', element: ['마르모어 코메트', '펜데록', '(폭탄)', '(금속)']},
  {material: '천계의 대청소', element: ['마르모어 코메트', '용핵', '(폭탄)', '(금속)']},
  {material: '하이터 슈토름', element: ['에르토나 수정', '(연료)', '(금속)', '(중화제)']},
  {material: '슈네 스토름', element: ['에르토나 수정', '(물)', '(기체)', '(중화제)']},
  {material: '명랑 장난감 상자', element: ['발파용 프람', '(푸니푸니구슬)', '(신비의힘)', '(마법의도구)']},
  {material: '깜짝 선물', element: ['명랑 장난감 상자', '(종이)', '(화약)', '(폭탄)']},
  {material: '원초의 불씨', element: ['심홍석', '제트 원석', '(폭탄)', '(신비의힘)']},
  {material: '일구입혼 메테오 볼', element: ['금강석', '무두질 가죽', '(금속)', '(에릭실)']},
  {material: 'N/A', element: ['오리프람', '슈탈 레헤른', '도나 크리스털', '루프트 아이젠']},
  {material: '리퓨얼 패트', element: ['백설풀', '(마법의풀)', '(약재료)']},
  {material: '소박한 구운과자', element: ['성게', '보릿가루', '(물)']},
  {material: '푸니젤리', element: ['꿀', '(푸니푸니구슬)', '(물)', '(과일)']},
  {material: '빨강 푸니젤리', element: ['허니 시럽', '푸니푸니 구슬 적', '(물)', '(과일)']},
  {material: '리퓨얼 보틀', element: ['코발트 풀', '(약재료)', '(물)', '(중화제)']},
  {material: '원초의 힘고기', element: ['짐승 고기', '튼튼한 뼈', '(기름)', '(식재)']},
  {material: '프루티', element: ['감로의 열매', '식용수', '(과일)', '(꽃)']},
  {material: '스위티', element: ['꿀', '업콜', '(물)', '(향기)']},
  {material: '산들바람 아로마', element: ['퓨어 오일', '(향기)', '(약재료)', '(종이)']},
  {material: '허니 시럽', element: ['꿀', '(약품)', '(물)']},
  {material: '재생의 이슬', element: ['별모래 물', '(약재료)', '(기체)', '(에릭실)']},
  {material: '생명의 꿀', element: ['황금나뭇잎', '(에릭실)', '(신비의힘)', '(중화제)']},
  {material: '라위의 비약', element: ['웜 피시', '(약재료)', '(버섯)', '(물)']},
  {material: '신비의 영약', element: ['던켈하이트', '(에릭실)', '(물)', '(중화제)']},
  {material: '특제 핫케이크', element: ['꿀', '무언가의 알', '보릿가루', '(물)']},
  {material: '소악마의 장난', element: ['수상한 액체', '(독재료)', '(금속)', '(신비의힘)']},
  {material: '퓨어 아로마', element: ['퓨어 오일', '(꽃)', '(향기)', '(연료)']},
  {material: '산성 안개구름', element: ['자연광물유', '수상한 액체', '(연료)', '(독재료)']},
  {material: '메디아 비독', element: ['어둠 버섯', '(버섯)', '(독재료)', '(푸니푸니구슬)']},
  {material: '암흑수', element: ['메디아 비독', '(독재료)']},
  {material: '만능 액막이 향', element: ['키큰 톤', '(향기)', '(종이)', '(연료)']},
  {material: '정령의 장막', element: ['점은실', '(직물)', '(실소재)', '(신비의힘)']},
  {material: '영웅의 환약', element: ['용의 비늘', '(에릭실)', '(식재)', '(중화제)']},
  {material: '트리톤의 소라고둥', element: ['일각', '(금속)', '(에릭실)', '(중화제)']},
  {material: '힘멜 릴리프', element: ['깨진 석재', '다색 염료', '제텔', '(점토)']},
  {material: '극채색 파우더', element: ['다색 염료', '(꽃)', '(모래)', '(광석)']},
  {material: '천매간', element: ['증류수', '(마법의풀)', '(꽃)', '(중화제)']},
  {material: '프리즈마 크리스털', element: ['수정 조각', '폴리시', '(물)', '(중화제)']},
  {material: '언펠라이트', element: ['그라나트', '(기름)', '(연료)', '(중화제)']},
  {material: '빙무의 스틱', element: ['만년무빙', '(물)', '(중화제)']},
  {material: '클러스터 코인', element: ['골드 아이젠', '(보석)', '(중화제)']},
  {material: '나선 시계판', element: ['그라비석', '(무기소재)', '(신비의힘)', '(중화제)']},
  {material: '별의 분무', element: ['별모래 물', '다색 염료', '(금속)', '(신비의힘)']},
  {material: '흑백의 타로', element: ['제텔', '다색 염료', '검은 모래', '하얀 모래']},
  {material: '피전 블러드 오일', element: ['메르베유 루즈', '(기름)', '(중화제)']},
  {material: '낚싯대', element: ['맛있어 보이는 떡밥', '(목재)', '(실소재)']},
  {material: '고품질 낚싯대', element: ['낚싯대', '맛있어 보이는 떡밥', '(실소재)']},
  {material: '신간 르베르크라운', element: ['고품질 낚싯대', '맛있어 보이는 떡밥', '(금속)', '(신비의힘)']},
  {material: '벌레망', element: ['(실소재)', '(목재)', '(금속)']},
  {material: '경량 벌레망', element: ['벌레망', '플뤼겔', '(신비의힘)', '(중화제)']},
  {material: '물주머니', element: ['무두질 가죽', '(기름)', '(실소재)', '(금속)']},
  {material: '특별 영양제', element: ['(식물류)', '(어패류)', '(약재료)', '(물)']},
  {material: '작은 요정의 가루', element: ['(직물)', '(실소재)', '(신비의힘)', '(중화제)']},
  {material: '풍신의 가루', element: ['작은 요정의 가루', '(기체)', '(에릭실)', '(중화제)']},
  {material: '특제 백팩', element: ['무두질 가죽', '(신비의힘)', '(실소재)']},
  {material: '채집 장갑', element: ['(동물소재)', '(식물류)', '(실소재)']},
  {material: '발파용 프람', element: ['황금색 암석', '(화약)', '(연료)', '(중화제)']},
  {material: '초 발파용 프람', element: ['발파용 프람', '(화약)', '(연료)', '(기체)']},
  {material: '중화제 적', element: ['(연료)', '(물)']},
  {material: '중화제 청', element: ['(기름)', '(물)']},
  {material: '중화제 황', element: ['(점토)', '(물)']},
  {material: '중화제 녹', element: ['(식물류)', '(물)']},
  {material: '중화제 자', element: ['(독재료)', '(물)']},
  {material: '만능 중화제 무지개', element: ['증류수', '(중화제)', '(신비의힘)', '(에릭실)']},
  {material: '증류수', element: ['(물)', '(연료)']},
  {material: '꿀', element: ['(벌집)']},
  {material: '보릿가루', element: ['바이체 보리']},
  {material: '업콜', element: ['장딸기', '(식물류)', '(물)']},
  {material: '퓨어 오일', element: ['식물유', '(식물류)', '(중화제)']},
  {material: '제텔', element: ['(식물류)', '(물)', '(중화제)']},
  {material: '무두질액', element: ['수상한 액체', '(마법의풀)', '(물)', '(중화제)']},
  {material: '무두질 가죽', element: ['동물의 가죽', '무두질액', '(실소재)', '(중화제)']},
  {material: '다색 염료', element: ['자연광물유', '(꽃)', '(물)', '(곤충)']},
  {material: '폴리시', element: ['백회색', '(물)', '(점토)', '(연료)']},
  {material: '연금점토', element: ['(점토)', '(신비의힘)', '(약품)', '(중화제)']},
  {material: '원초의 재', element: ['황금나뭇잎', '(마법의도구)', '(목재)', '(연료)']},
  {material: '지구의 구슬', element: ['다색 염료', '(목재)', '(종이)']},
  {material: '맛있어 보이는 떡밥', element: ['보릿가루', '(곤충)', '(어패류)', '(식재)']},
  {material: '잉곳', element: ['(광석)', '(연료)']},
  {material: '실베리아', element: ['쿠플흐 광석', '소울 스톤', '(금속)', '(연료)']},
  {material: '골드 아이젠', element: ['아이젠 광석', '황금색 암석', '(금속)', '(연료)']},
  {material: '하르모늄', element: ['심홍석', '정령석', '(금속)', '(연료)']},
  {material: '클로스', element: ['(실소재)', '(식물류)', '(동물소재)']},
  {material: '모프코트', element: ['야면화', '(실소재)', '(동물소재)', '(직물)']},
  {material: '플뤼겔', element: ['마조의 깃털', '(기체)', '(실소재)', '(직물)']},
  {material: '벨베티스', element: ['금견실', '만능 중화제 무지개', '(에릭실)', '(직물)']},
  {material: '제트 원석', element: ['칠흑의 도목석', '연금점토', '(물)']},
  {material: '그라나트 원석', element: ['소울 스톤', '연금점토', '(물)']},
  {material: '에메랄드 원석', element: ['물결 바위', '연금점토', '(물)']},
  {material: '사파이어스 원석', element: ['자철암', '연금점토', '(연료)', '(물)']},
  {material: '루비나이트 원석', element: ['자철암', '연금점토', '(연료)', '(물)']},
  {material: '금강 원석', element: ['킴버 광석', '연금점토', '폴리시', '(물)']},
  {material: '제트', element: ['제트 원석', '폴리시', '(물)', '(중화제)']},
  {material: '그라나트', element: ['그라나트 원석', '폴리시', '(물)', '(중화제)']},
  {material: '에메랄드', element: ['에메랄드 원석', '폴리시', '(물)', '(중화제)']},
  {material: '사파이어스', element: ['사파이어스 원석', '폴리시', '증류수', '(중화제)']},
  {material: '루비나이트', element: ['루비나이트 원석', '폴리시', '증류수', '(중화제)']},
  {material: '금강석', element: ['금강 원석', '폴리시', '증류수', '(중화제)']},
  {material: '마르모어 코메트', element: ['칠흑의 성석', '폴리시', '증류수', '(중화제)']},
  {material: '심홍석', element: ['용의 혈정', '쌍색 커런덤', '(화약)', '(에릭실)']},
  {material: '현자의 돌', element: ['심홍석', '원초의 재', '(에릭실)', '(보석)']},
  {material: '귀여운 현자의 돌', element: ['심홍석', '원초의 재', '(용소재)', '(에릭실)']},
  {material: '활성제', element: ['(푸니푸니구슬)', '(곤충)', '(기름)', '(중화제)']},
  {material: '바르하이트', element: ['옥강석', '황금색 암석', '(연료)']},
  {material: '액화금속', element: ['자철암', '수상한 액체', '(기름)']},
  {material: '가열도석', element: ['연금점토', '(화약)', '(모래)', '(연료)']},
  {material: '과반응 유지', element: ['황금색 암석', '(곤충)', '(연료)', '(기름)']},
  {material: '적기문석', element: ['사악한 송곳니', '마르모어 코메트', '(보석)', '(연료)']},
  {material: '성산', element: ['찌릿찌릿물', '산성 안개구름', '(에릭실)', '만능 중화제 무지개']},
  {material: '용산', element: ['심핵', '산성 안개구름', '(용소재)', '만능 중화제 무지개']},
  {material: '심창석', element: ['창강석', '원초의 재', '던켈하이트', '만능 중화제 무지개']},
  {material: '꿈의 붓', element: ['코발트 풀', '(목재)', '(실소재)', '(중화제)']},
  {material: '꿈의 붓?', element: ['코발트 풀', '(목재)', '(실소재)']},
  {material: '고고한 마음의 물감', element: ['미스틱 허브', '(광석)', '(기름)', '(신비의힘)']},
  {material: '고상한 파도의 물감', element: ['(화약)', '(모래)', '(기름)', '(신비의힘)']},
  {material: '얼어붙은 심상의 물감', element: ['(물)', '(연료)', '(기름)', '(신비의힘)']},
  {material: '틈새를 떠도는 물감', element: ['눈의 여왕', '(물)', '(기름)', '(신비의힘)']},
  {material: '영원한 천상의 물감', element: ['푸니푸니 구슬 금', '(과일)', '(기름)', '(신비의힘)']},
  {material: '꿈꾸는 밤하늘의 물감', element: ['(에릭실)', '(꽃)', '(기름)', '(신비의힘)']},
  {material: '사악한 어둠에 떨어진 물감', element: ['(용소재)', '(곤충)', '(기름)', '(신비의힘)']},
  {material: '끝이 없는 일기장', element: ['제텔', '황금나뭇잎', '(에릭실)', '(신비의힘)']},
  {material: '커뮤테이션', element: ['쌍색 커런덤', '업콜', '(약재료)']},
  {material: '아다렛트 장미보관', element: ['골드 아이젠', '메르베유 루즈', '(보석)']},
  {material: '얼음상자', element: ['레헤른', '(물)', '(목재)', '(신비의힘)']},
  {material: '도나 엔데커', element: ['도나 스톤', '옥강석', '(금속)']},
  {material: '냉풍 기관', element: ['레헤른', '(기체)', '(금속)', '(신비의힘)']},
  {material: '고블릿', element: ['에르토나 수정', '폴리시', '(금속)']},
  {material: '은식기 세트', element: ['실베리아', '폴리시', '증류수', '(중화제)']},
  {material: '위장약', element: ['촉촉한 풀', '(푸니푸니구슬)', '(약재료)', '(벌집)']},
  {material: '감기 특효약', element: ['대형 알', '업콜', '(약재료)', '(푸니푸니구슬)']},
  {material: '액화용제', element: ['마르모어 코메트', '푸니 체엑', '만능 중화제 무지개']},
  {material: '활력의 얼리언스', element: ['(보석)', '(무기소재)', '(신비의힘)']},
  {material: '용맹의 얼리언스', element: ['그라나트', '폴리시', '(보석)', '(무기소재)']},
  {material: '맹력의 브라존', element: ['연금점토', '(무기소재)', '(동물소재)', '(신비의힘)']},
  {material: '신력의 브라존', element: ['하르모늄', '(보석)', '(신비의힘)']},
  {material: '광속의 오브', element: ['그라비석', '(보석)', '(무기소재)', '(중화제)']},
  {material: '신속의 오브', element: ['펜데록', '(보석)', '(무기소재)', '(중화제)']},
  {material: '쾌도난마의 엠블럼', element: ['커다란 비늘', '폴리시', '(무기소재)', '(금속)']},
  {material: '일기당천 오르뎀', element: ['용핵', '만능 중화제 무지개', '(무기소재)', '(금속)']},
  {material: '예지의 리안', element: ['쌍색 커런덤', '정령석', '(무기소재)', '(신비의힘)']},
  {material: '쿼츠 기어', element: ['수정 조각', '(금속)', '(신비의힘)', '(중화제)']},
  {material: '카보숑 기어', element: ['창강석', '성수', '(금속)', '(중화제)']},
  {material: '제트 기어', element: ['제트', '잉곳', '(금속)']},
  {material: '에메랄드 파멀', element: ['에메랄드', '실베리아', '(보석)', '(중화제)']},
  {material: '사파이어스 파멀', element: ['사파이어스', '실베리아', '(보석)', '(중화제)']},
  {material: '루비나이트 파멀', element: ['루비나이트', '실베리아', '(보석)', '(중화제)']},
  {material: '마르모어 기어', element: ['마르모어 코메트', '하르모늄', '(보석)', '(신비의힘)']},
  {material: '금강 룬스톤', element: ['금강석', '하르모늄', '(금속)']},
  {material: '그나데링', element: ['(보석)', '(금속)', '(실소재)', '(신비의힘)']},
  {material: '엔젤리본', element: ['금견실', '(직물)', '(보석)', '(신비의힘)']},
  {material: '불꽃의 탈리스만', element: ['오리프람', '중화제 적', '(금속)', '(보석)']},
  {material: '바람의 탈리스만', element: ['루프트 아이젠', '중화제 녹', '(금속)', '(보석)']},
  {material: '얼음의 탈리스만', element: ['슈탈 레헤른', '중화제 청', '(금속)', '(보석)']},
  {material: '뇌환의 탈리스만', element: ['도나 크리스털', '중화제 황', '(금속)', '(보석)']},
  {material: '마석 체인', element: ['에메랄드', '루비나이트', '사파이어스', '(보석)']},
  {material: '너클 가드', element: ['아이젠 광석', '(금속)', '(직물)', '(실소재)']},
  {material: '행운의 금화', element: ['금강 원석', '(금속)', '(동물소재)', '(보석)']},
  {material: '안쥬 파뤼르', element: ['골드 아이젠', '(보석)']},
  {material: '용린의 목걸이', element: ['용의 비늘', '(신비의힘)', '(실소재)', '(향기)']},
  {material: '스파이크 부츠', element: ['무두질 가죽', '(금속)', '(실소재)']},
  {material: '특별비약영양제', element: ['특별 영양제', '(어패류)', '(약재료)', '(물)']},
  {material: '비밀 백', element: ['특제 백팩', '(금속)', '(실소재)', '(신비의힘)']},
  {material: '창세의 브라존', element: ['심홍석', '하르모늄', '(신비의힘)', '(무기소재)']},
  {material: '용맹무쌍의 파라심', element: ['위대한 꼬리', '하르모늄', '(금속)', '(무기소재)']},
  {material: '대현자의 스피라', element: ['심핵', '하르모늄', '(보석)', '(신비의힘)']},
  {material: '왕의 리안', element: ['용핵', '하르모늄', '(신비의힘)', '(무기소재)']},
  {material: '조화의 아겐트', element: ['던켈하이트', '하르모늄', '(무기소재)']},
  {material: '윈터르 카푸트', element: ['빙무의 스틱', '원초의 재', '(보석)', '(중화제)']},
  {material: '서머르 카푸트', element: ['언펠라이트', '원초의 재', '(보석)', '(중화제)']},
  {material: '폴스 레겐', element: ['정령석', '만능 중화제 무지개', '(보석)', '(금속)']},
  {material: '앱소브 카푸트', element: ['사악한 뼈', '원초의 재', '(보석)', '(중화제)']},
  {material: '뢰베르 기어', element: ['쌍색 커런덤', '심홍석', '(금속)']},
  {material: '백열머리띠', element: ['모프코트', '실베리아', '(직물)', '(실소재)']},
  {material: '정령의 이어링', element: ['힘멜 릴리프', '펜데록', '(보석)', '(금속)']},
  {material: '모노크롬 안경', element: ['칠흑의 성석', '(금속)', '(약재료)', '(독재료)']},
  {material: '시간조종 모래시계', element: ['흑백의 타로', '나선 시계판', '(모래)']},
  {material: '광휘의 탈리스만', element: ['하이터 슈토름', '경건한 신자용 부적', '(보석)', '(중화제)']},
  {material: '월화의 탈리스만', element: ['슈네 슈토름', '미스틱 허브', '(보석)', '(중화제)']},
  {material: '불사조의 반지', element: ['빙무의 스틱', '(동물소재)', '(신비의힘)', '(에릭실)']},
  {material: '탐보의 그리모어', element: ['현자의 돌', '피전 블러드 오일', '(용소재)', '(종이)']},
  {material: '투명 망토', element: ['플뤼겔', '박쥐 날개', '(실소재)', '(에릭실)']},
  {material: '브리츠 코어 화', element: ['수정 조각', '아이젠 광석', '(연료)', '(중화제)']},
  {material: '브리츠 코어 빙', element: ['수정 조각', '아이젠 광석', '(물)', '(중화제)']},
  {material: '브리츠 코어 뇌', element: ['수정 조각', '아이젠 광석', '(광석)', '(중화제)']},
  {material: '브리츠 코어 풍', element: ['수정 조각', '아이젠 광석', '(기체)', '(중화제)']},
  {material: '사나이의 누름돌', element: ['소형 하겔상', '(모래)', '(연료)', '(중화제)']},
  {material: '차원폭탄', element: ['천계의 대청소', '종말의 불씨', '깜짝 선물', '(중화제)']},
  {material: '오메가 크래프트', element: ['크래프트', '골드 아이젠', '(화약)', '(기체)']},
  {material: '애플 타르트', element: ['눈의 여왕', '대형 알', '보릿가루', '(식재)']},
  {material: '전자동 버섯냄비', element: ['요정의 양산', '(버섯)', '(식재)', '(금속)']},
  {material: '강장분말약', element: ['사약한 뼈', '(약재료)', '(어패류)', '(용소재)']},
  {material: '불꽃의 망치', element: ['찌릿찌릿물', '(금속)', '(목재)']},
  {material: '강력사나이 기어', element: ['골드 아이젠', '(기름)', '(화약)', '(금속)']},
  {material: '싸움의 부적', element: ['무두질 가죽', '동물의 가죽', '(점토)', '(보석)']},
  {material: '두 사람의 물감', element: ['연금점토', '다색 염료', '(신비의힘)', '(에릭실)']}
]
